import { Prediction, PredictionLocation, RiskFilter, TimeFilter } from '../types';
import { MapPin, Clock, Target, AlertTriangle, ChevronRight, ChevronDown, ChevronUp, Shield, Activity, GitBranch, History, Download } from 'lucide-react';
import { useState } from 'react';
import AnimatedNumber from './AnimatedNumber';

interface PredictionCardProps {
  prediction: Prediction;
  onShowEvidence: () => void;
}

const evidenceIcons: Record<string, React.ReactNode> = {
  transaction_pattern: <Activity size={14} className="text-[#e4e4e7]" />,
  temporal_pattern: <Clock size={14} className="text-[#e4e4e7]" />,
  geographic_signal: <MapPin size={14} className="text-[#e4e4e7]" />,
  account_network: <GitBranch size={14} className="text-[#e4e4e7]" />,
  historical_similarity: <History size={14} className="text-[#e4e4e7]" />,
};

function downloadReport(prediction: Prediction) {
  const p = prediction.primary_location;
  const lines = [
    `INTELLIGENCE REPORT — CASH-OUT PREDICTION`,
    `Generated: ${new Date().toISOString()}`,
    `Case ID: ${prediction.case_id}`,
    `Status: ${prediction.status}`,
    ``,
    `PREDICTED CASH-OUT LOCATION`,
    `  ATM ID: ${p.atm_id}`,
    `  Location: ${p.location_name}`,
    `  Risk Score: ${p.risk_score}%`,
    `  Time Window: ${p.expected_window}`,
    `  Distance from center: ${p.distance}`,
    `  Coordinates: ${p.latitude}, ${p.longitude}`,
    ``,
    `EVIDENCE SIGNALS`,
    ...Object.entries(prediction.evidence).map(([key, item]) =>
      `  [${item.strength}] ${item.category}: ${item.description}`
    ),
    ``,
    `RANKED LOCATIONS`,
    ...prediction.ranked_locations.map((loc, i) =>
      `  ${i + 1}. ${loc.atm_id} — ${loc.location_name} (Risk: ${loc.risk_score}%, Distance: ${loc.distance})`
    ),
    ``,
    `RISK TREND (Last 6 Hours)`,
    ...prediction.risk_trend.map((value, i) =>
      `  ${18 + i}:00 — Risk: ${value}%`
    ),
    ``,
    `---`,
    `CONFIDENTIAL — Law Enforcement Use Only`,
    `Generated by ATLAS Predictive Analytics Engine v4.0`,
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ATLAS_Report_${prediction.case_id}_${new Date().toISOString().split('T')[0]}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function PredictionCard({ prediction, onShowEvidence }: PredictionCardProps) {
  const p = prediction.primary_location;
  const [showEvidence, setShowEvidence] = useState(false);
  const evidence = Object.entries(prediction.evidence);

  return (
    <div className="card p-5">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <AlertTriangle size={14} className="text-[#ef4444]" />
            <span className="text-sm font-medium text-[#ef4444]">{prediction.status}</span>
          </div>
          <span className="text-sm text-[#d4d4d8] bg-[#27272a] px-2 py-0.5 rounded font-mono">{prediction.case_id}</span>
        </div>
      </div>

      {/* Main Prediction Focus */}
      <div className="bg-[#0a0a0f] rounded-xl p-4 border border-[#27272a] mb-4">
        <div className="text-sm text-[#d4d4d8] uppercase tracking-wider mb-2">Predicted Cash-Out Location</div>
        <div className="flex items-center gap-3 mb-3">
          <MapPin size={18} className="text-white" />
          <span className="text-2xl font-bold text-white">{p.atm_id}</span>
          <span className="text-[#d4d4d8]">—</span>
          <span className="text-[#e4e4e7]">{p.location_name}</span>
        </div>

        <div className="grid grid-cols-3 gap-3">
          <div className="bg-[#18181b] rounded-lg p-3 border border-[#27272a]">
            <div className="text-[10px] text-[#d4d4d8] uppercase tracking-wider mb-1">Risk Index</div>
            <div className={`text-2xl font-bold ${
              p.risk_score > 70 ? "text-[#ef4444]" : p.risk_score > 45 ? "text-[#f59e0b]" : "text-[#d4d4d8]"
            }`}>
              <AnimatedNumber value={p.risk_score} suffix="%" />
            </div>
            <div className="text-[10px] text-[#71717a] mt-0.5">
              {p.risk_score > 70 ? "Critical" : p.risk_score > 45 ? "Elevated" : "Normal"} · Not a calibrated probability
            </div>
          </div>
          <div className="bg-[#18181b] rounded-lg p-3 border border-[#27272a]">
            <div className="text-[10px] text-[#d4d4d8] uppercase tracking-wider mb-1">Time Window</div>
            <div className="text-lg font-bold text-white">{p.expected_window}</div>
            <div className="text-[10px] text-[#d4d4d8] mt-0.5">Expected</div>
          </div>
          <div className="bg-[#18181b] rounded-lg p-3 border border-[#27272a]">
            <div className="text-[10px] text-[#d4d4d8] uppercase tracking-wider mb-1">Distance</div>
            <div className="text-lg font-bold text-white">{p.distance}</div>
            <div className="text-[10px] text-[#d4d4d8] mt-0.5">From center</div>
          </div>
        </div>
      </div>

      {/* Why This Location - Evidence Signals */}
      <div className="mb-4">
        <button
          onClick={() => setShowEvidence(!showEvidence)}
          className="w-full flex items-center justify-between p-3 bg-[#0a0a0f] rounded-lg border border-[#27272a] hover:border-[#71717a] transition-colors"
        >
          <div className="flex items-center gap-2">
            <Shield size={14} className="text-white" />
            <span className="text-base font-medium text-white">Why this location?</span>
            <span className="text-[10px] text-[#d4d4d8] bg-[#27272a] px-1.5 py-0.5 rounded">{evidence.length > 0 ? `${evidence.length} signals` : 'Loading...'}</span>
          </div>
          {showEvidence ? <ChevronUp size={14} className="text-[#d4d4d8]" /> : <ChevronDown size={14} className="text-[#d4d4d8]" />}
        </button>

        {showEvidence && (
          <div className="mt-2 space-y-2">
            {evidence.map(([key, item]) => (
              <div key={key} className="flex items-start gap-3 p-2.5 bg-[#0a0a0f] rounded-lg border border-[#27272a]">
                {evidenceIcons[key] || <Shield size={14} className="text-[#e4e4e7]" />}
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-sm font-medium text-white">{item.category}</span>
                    <span className={`text-[10px] px-1 py-0.5 rounded ${
                      item.strength === "Strong" ? "bg-[#22c55e]/10 text-[#22c55e]" :
                      item.strength === "Moderate" ? "bg-[#f59e0b]/10 text-[#f59e0b]" :
                      "bg-[#27272a] text-[#d4d4d8]"
                    }`}>
                      {item.strength}
                    </span>
                  </div>
                  <p className="text-[11px] text-[#d4d4d8]">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="flex gap-2">
        <button
          onClick={onShowEvidence}
          className="flex-1 py-2.5 bg-white text-black text-base font-medium rounded-lg hover:bg-[#e4e4e7] transition-colors flex items-center justify-center gap-2"
        >
          View Full Evidence <ChevronRight size={14} />
        </button>
        <button
          onClick={() => downloadReport(prediction)}
          className="py-2.5 px-4 bg-[#27272a] text-white text-base font-medium rounded-lg hover:bg-[#71717a] transition-colors flex items-center justify-center gap-2"
          title="Download Intelligence Report"
        >
          <Download size={14} />
          Report
        </button>
      </div>
    </div>
  );
}

export function PredictionCardSkeleton() {
  return (
    <div className="card p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="h-4 w-20 bg-[#27272a] rounded animate-pulse" />
        <div className="h-4 w-24 bg-[#27272a] rounded animate-pulse" />
      </div>
      <div className="bg-[#0a0a0f] rounded-xl p-4 border border-[#27272a] mb-4">
        <div className="h-3 w-32 bg-[#27272a] rounded animate-pulse mb-2" />
        <div className="h-8 w-48 bg-[#27272a] rounded animate-pulse mb-3" />
        <div className="grid grid-cols-3 gap-3">
          <div className="h-20 bg-[#27272a] rounded-lg animate-pulse" />
          <div className="h-20 bg-[#27272a] rounded-lg animate-pulse" />
          <div className="h-20 bg-[#27272a] rounded-lg animate-pulse" />
        </div>
      </div>
      <div className="h-10 bg-[#27272a] rounded-lg animate-pulse" />
    </div>
  );
}
